### ISSUE TITLE
z_Install_O4XP_macOS_Python3.11_Venv.sh Does Not Work

### ISSUE THREAD

**Issue by OldSubSailor** [w8sl/Ortho4XP#4]
I tried running the script on an iMac, Ventura 13.6.7 and it simply failed.  No error messages were generated that I noticed. 
1. The Homebrew formulas were never installed.
2. The macOS system Python3.9 was called and used in all steps. This resulted in the use the system version of Tk which failed as per the depreciation warning and presented a blank white Ortho4XP 1.40 window.
3. Pip listing is:
% pip3 list
Package Version
------- -------
GDAL    3.9.0
gpg     1.23.2
numpy   1.26.4
pip     24.0
wheel   0.43.0

I manually entered the brew packages and tried running it again (using z_Start_O4XP script), but still no better luck. 
./z_Start_O4XP_PythonVenv.sh
/Users/trav/Ortho4XP-master/venv-ortho/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

![Ortho4XP1 40jpg](https://github.com/w8sl/Ortho4XP/assets/54075170/41300a48-bb8d-4da4-bce9-adb1d97a732a)

**Comment by w8sl** [comment]
I have noticed that spaces are not allowed in directory names, when running venv script. It is macOS feature, nothing I can fix. Standard install script should work. PATH is also different on Intel Mac as described in my install instructions.

**Comment by w8sl** [comment]
"Brew install" line is commented out intentionally as it is only needed once. Then, it is possible to create separate install environment for every version of O4XP. Space is not allowed in the last part of directory name for some reason.

**Comment by w8sl** [comment]
First uncomment line with "brew install" command inside the script. The one without "3.11" in name will actually install python3.12 venv, but brew install part must be run first.

**Comment by OldSubSailor** [comment]
**That was uncommented as per the instructions**,  but I never saw anything saying that the formulas were being installed on the terminal screen. Do they not scroll down?
_but "brew install" part,_  I take that you mean Installing Homebrew itself?
Still, I ended up with a Tk that did not work as shown in the screenshot above, it still looked like the native macOS version of Python was being called, which was causing the depreciated Tk call. 

What is venv exactly?

**Comment by w8sl** [comment]
brew install gdal python@3.11 python-tk@3.11 proj spatialindex p7zip

You can run this line separately as it is system-wide install. Then run 3.11 venv script "as is". Of course Homebrew is needed. venv is virtual environment contained in venv-ortho directory

**Comment by OldSubSailor** [comment]
I had to run the brew install line separately, seeing as how they did not run as expected. Still no joy, and I ended up with the python3.9 running out of the macOS Command Line install.

**Comment by w8sl** [comment]
The nice thing about venv is: if it is broken, just delete venv-ortho directory inside your Ortho4XP-master folder and run venv3.11 install script again

**Comment by OldSubSailor** [comment]
I tried various attempts and decided to abandon the Venv all together. I am trying the simple command line approach now.

**Comment by w8sl** [comment]
"custom_overlay_src" should be set to: "../X-Plane 12/Global Scenery/X-Plane 12 Global Scenery" directory.  
It must be XP12!   
XP12 installer "Update Scenery" will check for corrupted files.

**Comment by OldSubSailor** [comment]
I am trying to get back to XP11 (XP12 it too much for it)on the iMac. I kept my old version of 1.3 but now can not get it to run after reinstalling Homebrew and the formulas and the pip packages. Upon calling it with Python3.11,  It will come up with a terminal screen full of:   _/Users/trav/Ortho4XP-master/./src/O4_Airport_Utils.py:322: ShapelyDeprecationWarning: The 'cascaded_union()' function is deprecated. Use 'unary_union()' instead._
 
Then on step one it runs and halts with:
full_area=VECT.ensure_MultiPolygon(ops.cascaded_union([dico_airports[airport]['boundary'],dico_airports[airport]['runway'][0],dico_airports[airport]['hangar'],dico_airports[airport]['taxiway'][0],dico_airports[airport]['apron'][0]]))
Exception in thread Thread-2 (build_poly_file):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/trav/Ortho4XP-master/./src/O4_Vector_Map.py", line 42, in build_poly_file
    (apt_array,apt_area)=include_airports(vector_map,tile) 
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trav/Ortho4XP-master/./src/O4_Vector_Map.py", line 138, in include_airports
    APT.smooth_raster_over_airports(tile,dico_airports)
  File "/Users/trav/Ortho4XP-master/./src/O4_Airport_Utils.py", line 429, in smooth_raster_over_airports
    for polygon in full_area:
TypeError: 'MultiPolygon' object is not iterable

**Comment by w8sl** [comment]
pip3 install shapely==1.8.5
pip3 install numpy==1.23.5

This will solve your problem on Ventura

**Comment by w8sl** [comment]
z_Install_O4XP_macOS_Python3.11_Venv.sh does work semi-automatically now
Please let me know if you need file adapted for 1.30 or even 1.30 + Sonoma

**Comment by OldSubSailor** [comment]
OK, great, I knew that we had done something like that in the past. I had tried some older things and they would not fly; something about wheel install failures. Then there was an error message about "rounding".  
I also thought that you even had two versions of Ortho4XP for DownLoad at one time, i.e one for 1.3 & 1.4?

I am away from my Sonoma Mac mini by over 3 hours. Again on a 2017 iMac, Ventura 13.6.7.

I am still confused, but you are the genius:
I do not know if it was because of the Ventura OS, but when I did try running the script for Venv, and I did uncomment, I still do not understand why the homebrew installs did not go through, it did appear that the pip installs did.  I have since removed the Commandlines Python3.9 which appeared to be the Tk problem. But given that 1.4 is for XP12, and I no longer have it installed, I really do not see any reason to mess with it, unless you want me to experiment with it to get more information for you??

**Comment by OldSubSailor** [comment]
this is my current listing:
% pip3.11 list                  
Package            Version
------------------ ---------
certifi            2023.7.22
chardet            4.0.0
charset-normalizer 3.3.2
idna               2.10
numpy              1.23.5
pillow             10.2.0
pip                24.0
pyproj             3.6.1
requests           2.31.0
Rtree              0.9.7
scikit-fmm         2023.4.2
Shapely            1.8.5
urllib3            1.26.18
wheel              0.43.0


Do I need to remove any, say scikit to run 1.3?

**Comment by w8sl** [comment]
No you don't need to change anything. Even 1.40 will run with this setup

**Comment by OldSubSailor** [comment]
Along the lines of:
/Users/trav/Ortho4XP-master/./src/O4_Airport_Utils.py:268: ShapelyDeprecationWarning: The 'cascaded_union()' function is deprecated. Use 'unary_union()' instead.
  runway_area=VECT.ensure_MultiPolygon(ops.cascaded_union([item[0] for item in runways_as_area+runways_as_line]))


/Users/trav/Ortho4XP-master/./src/O4_Airport_Utils.py:471: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  (linestring,polyfit)=VECT.least_square_fit_altitude_along_way(center_way,steps,tile.dem,weights=True) 

Step 1 Returned a page full of terminal warnings attached as a zip file.

[TerminalWarnings.txt.zip](https://github.com/w8sl/Ortho4XP/files/15448313/TerminalWarnings.txt.zip)

**Comment by OldSubSailor** [comment]
We have worked through 1.4 on Sonoma with the mini.

**Comment by OldSubSailor** [comment]
The first run with 1.3 was pretty much a sacrifice zl 12, next to defaults settings, no zl airports. I will push it next.

**Comment by w8sl** [comment]
These warnings have been there for several years in 1.30. It is just information that 1.30 is outdated and will not run with latest packages.

pip3.11 install shapely==1.8.1 

may eventually work better than 1.8.5 in extreme cases (few tiles)

**Comment by OldSubSailor** [comment]
I have always seen the 100s of warnings when starting Ortho4 above step one, but do not recall the ones in step one.

**Comment by w8sl** [comment]
Progressive_130 branch on my fork doesn't have this problem + few more

**Comment by OldSubSailor** [comment]
I'm sorry, but I do not understand that statement.

**Comment by OldSubSailor** [comment]
It appears that the tile was made, but I got this final sequence of errors messages in terminal
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/trav/Ortho4XP-master/./src/O4_Parallel_Utils.py", line 18, in run
    self._success[0]= self._task(*args) and self._success[0] 
                      ^^^^^^^^^^^^^^^^^
  File "/Users/trav/Ortho4XP-master/./src/O4_Mask_Utils.py", line 311, in build_mask
    blur_width=[L/pxscal for L in tile.masks_width]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/trav/Ortho4XP-master/./src/O4_Parallel_Utils.py", line 18, in run
    self._success[0]= self._task(*args) and self._success[0] 
                      ^^^^^^^^^^^^^^^^^
  File "/Users/trav/Ortho4XP-master/./src/O4_Mask_Utils.py", line 311, in build_mask
    blur_width=[L/pxscal for L in tile.masks_width]

TypeError: 'int' object is not iterable
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/trav/Ortho4XP-master/./src/O4_Parallel_Utils.py", line 18, in run
    self._success[0]= self._task(*args) and self._success[0] 
                      ^^^^^^^^^^^^^^^^^
  File "/Users/trav/Ortho4XP-master/./src/O4_Mask_Utils.py", line 311, in build_mask
    blur_width=[L/pxscal for L in tile.masks_width]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable

**Comment by w8sl** [comment]
Which tile?

**Comment by w8sl** [comment]
When masking mode is set to: "3 steps"
Then masks width must be a list of 3 values like:
30,30,30   (Default is 100 which doesn't work in this case)

**Comment by OldSubSailor** [comment]
> When masking mode is set to: "3 steps", then masks_width must be a list of 3 integer values like: 30,30,30 (Default is 100 which doesn't work in this case)

ok, I did not that, but it sound familiar. Did the "old" version of 1.3 even remind us to do that even?

**Comment by OldSubSailor** [comment]
Tile and Settings

<img width="1019" alt="Ortho1 3" src="https://github.com/w8sl/Ortho4XP/assets/54075170/28105aff-42b8-4733-9ffb-93e907b84016">
<img width="978" alt="OrthoConfig" src="https://github.com/w8sl/Ortho4XP/assets/54075170/303d8b2d-1623-4e12-951f-6b75fb0ba019">
<img width="1129" alt="TilesCollection" src="https://github.com/w8sl/Ortho4XP/assets/54075170/20262dcd-73f1-4ffd-9781-f3aea645a1b3">

**Comment by OldSubSailor** [comment]
In this second run, I have changed Masks to this. 
<img width="237" alt="MASKS" src="https://github.com/w8sl/Ortho4XP/assets/54075170/7e890a9b-9dae-47f5-8f4a-c41b87eb6444">

**Comment by OldSubSailor** [comment]
> When masking mode is set to: "3 steps", then masks_width must be a list of 3 integer values like: 30,30,30 (Default is 100 which doesn't work in this case)

That appears to have been the issue. I created the tile again with the multiple values and although the Masks step took over an hour, there were no error/warnings.

**Comment by w8sl** [comment]
Instructions are displayed when pressing the grey button with variable name (masking_mode)

**Comment by OldSubSailor** [comment]
> Instructions are displayed when pressing the grey button with variable name (masking_mode, masks_width)

I understand that (and remembered as soon as you rang my bell), however, some are vague and dated. In the case of masking_mode I would suggest clarification is in order for non-programmers i.e. ". . . requires a list in the form of . . ." needs to be rewritten. 

I am sure that now I am getting far over my head. In the 3 steps, the entry is in the form of a tuple I think they are called?  I would suggest that for the 3 steps the instruction should be more direct (active voice) and state that it must be *_entered as three values (numbers), x,y,z as shown_ or even as you did above  * _as three values;  for example: 30,30,30 (as shown)_ . 

Then go a step further and use a conditional  to catch and remind the user that it must be *three numbers, if only one (or less than 3 ) is entered.

I am back from E. Texas, and will be away from the Ventura (and Ortho 1.3) iMac for about 3 weeks.

**Comment by w8sl** [comment]
I agree that Ortho4XP should not "just crash" without hint. A lot of work to be done. Most urgently needed is installer that checks which dependencies are missing and installs them automatically. That is what my venv installers are doing now on macOS. I will later add check for 3 steps masks to: https://github.com/w8sl/Ortho4XP/tree/Progressive_130
I am not sure what is the future of 3 steps masks on 1.40 and if they are still needed and used. 1.40 is work in progress. Some big changes are promised by the author in readme.

**Comment by OldSubSailor** [comment]
> I agree that Ortho4XP should not "just crash" without a hint. A lot of work to be done. Most urgently needed is installer that checks which dependencies are missing and installs them automatically. That is what my venv installers are doing now on macOS. I will later add check for 3 steps masks to: https://github.com/w8sl/Ortho4XP/tree/Progressive_130 I am not sure what is the future of 3 steps masks on 1.40 and if they are still needed and used. 1.40 is work in progress. Some big changes are promised by the author in readme.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I think that you have mentioned this.  Should we/you simply go ahead and make 1.40 Ventura & XP11 completely compatible and let 1.3 fade away?  Ventura machines are becoming legacy now, however, XP11 is not. 

That installer missing the brew formula installs _is or is not_ a concern and if not,  will it simply be clearly stated "manual" install as in days past?  I can sort of find my way around this stuff, but I do tend to forget or overlook at times, just like the list/tuple entry that I had forgotten about.

**Comment by w8sl** [comment]
macOS has just joined the club with disabled pip3 install to system-wide Python. It is now Arch Linux, Manjaro, Ubuntu24 and macOS. pip3.11 install and venv still works.

**Comment by w8sl** [comment]
There is no problem with 1.40 on Monterey and Ventura. XP11 is not supported due to different water triangulation, which is the main difference between 1.30 and 1.40

**Comment by OldSubSailor** [comment]
> Try again. Problem is solved. Another nice feature of venv is that it will not touch your current install.

I ran that on the intel iMac, which was doomed to begin with. XP11. On the Mac mini, I am indeed running Sonoma, and Ortho1.40, and an earlier April version (April 3, 2024 at 3:25 PM) that got from you, no issues so that is fine.

**Comment by OldSubSailor** [comment]
May as well close all this out then.

**Comment by w8sl** [comment]
scikit-fmm for Python12 was relased today but it is only possible to install in venv, as pip3 install is forbidden on Sonoma. We may well close the issue.
